### ISSUE TITLE
Does Not Restrict Pages

### ISSUE THREAD

**Issue by paulfeakins** [nliautaud/pico-users#4]
Is this plugin still supported? 

Does it work with Pico 1.0.6?

I've added to /plugins/ and added users and rights settings to config.php, but I can still browser all pages.

I'm using the default content, my settings are:

```
$settings['users'] = array
(
	'managers' => array(
		'cristina' => '2cc13a9e718d3d3051ac1f0ba024a2ff77485f4b',
		'paul' => '12dea96fec20593566ab75692c9949596833adc9'
	),
	'developers' => array(
		'aaron' => '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684',
		'james' => '12dea96fec20593566ab75692c9949596833adc9'
	)
);

$settings['rights'] = array
(
	'sub/index' => 'managers'
);
```

**Comment by paulfeakins** [comment]
I've also added this to config.php

`$config['_pico_users.enabled'] = true;`

**Comment by nliautaud** [comment]
Hello, I made an upgrade to Pico 1.0 in the following branch : 
https://github.com/nliautaud/pico-users/tree/v0.2
Could you test it before I release it ?

Note that the plugin will be enabled by default, and that `$config` has to be used instead. See the updated readme for up to date infos.

**Comment by paulfeakins** [comment]
Nice, that seems to work. 

It throws a 404 if you browse directly and it hides restricted pages from the menu for non-logged users.

**Comment by nliautaud** [comment]
Great, thanks !

Two precisions on features that I don't know if they are explicit enough :
- By default a standard 404 is thrown, that you can customize with the 404.md page. If you want to indicates to visitors that the pages exists but are restricted, you can create a 403.md page.
- You can restrict full directories by using a trailing slash in a rights rule.

**Comment by paulfeakins** [comment]
Yes, I read the docs and I understood both of these points easily!

**Comment by nliautaud** [comment]
Perfect, thanks for your return. I'll roll it shortly then.
